CREATE DATABASE IF NOT EXISTS dog_app;
CREATE DATABASE IF NOT EXISTS slime_shop;
CREATE DATABASE IF NOT EXISTS soap_store;

SHOW DATABASES;

DROP DATABASE dog_app;
DROP DATABASE slime_shop;
DROP DATABASE soap_store;

USE dog_app;

SELECT DATABASE();